### ISSUE TITLE
RPC username cannot be set

### ISSUE THREAD

**Issue by adripo** [linuxserver/docker-transmission#212] opened 2022-10-31 02:17 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Trying to log from browser will only work with `root` as user and the `USER` configured as ENV during `docker run` will not work.
More details on my config and results inside [Current Behavior](#current-behavior)

------------------------------

## Expected Behavior

- Login from browser should work with set `USER`
- Environment variable `USER` == `USER` variable set during docker run

<a id="current-behavior"></a>
## Current Behavior

docker compose:
```
...
    environment:
      - USER=admin
      - PASS=noteasypassword
...
```

inside the container:
```
root@76025c92219f:/# env
PUID=1000
HOSTNAME=76025c92219f
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
PWD=/
HOME=/root
PGID=1000
TERM=xterm
USER=root
PASS=noteasypassword
SHLVL=1
PS1=$(whoami)@$(hostname):$(pwd)\$ 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TRANSMISSION_WEB_HOME=/transmission-web-control
_=/usr/bin/env
```

## Steps to Reproduce

1. Set `USER` ENV during `docker run`
2. `docker exec` inside the container
3. print `env`
4. `USER=root` and not the value set during run
5. Trying to log from browser will only work with `root` as user

## Environment
**OS:-**
**CPU architecture:** x86_64
**How docker service was installed:**

**Comment by aptalca** [comment] 2022-10-31 03:48
You likely did not recreate the container, or did not set the env vars correctly.

You're providing conflicting and incomplete information.

You show us a yaml snippet for two env vars, yet you're saying you're doing `docker run`.

This seems like user error but we don't have enough info to determine what type. Closing as it is not a bug. We have other channels for config help.

**Closed by aptalca** 2022-10-31 03:48 UTC

**Comment by adripo** [comment] 2022-11-01 23:33
@aptalca Thanks for your answer. I tested a clean version and you are right, everything works as expected.
After a little more digging I discovered what my problem is:

My docker-compose is something like this:

```docker-compose.yml
services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission
    ports:
      - "9091:9091"
      - "31413:51413"
      - "31413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/transmission-web-control
    env_file:
      - transmission.env
    volumes:
    ...
```

and the `transmission.env` file contains:
```
USER=admin
PASS=secret-password
```

Using an external env file for the `USER` will not work and will always be overwritten with `root`. I think this happens because the moment when the env file is loaded is different from when the `environment` section in docker-compose is loaded, so it gets the default user root. Do you have any clue on that?

**Comment by adripo** [comment] 2022-11-01 23:50
@aptalca I have done some more tests and I have more clues on the issue, still cannot resolve it.

The issue happens when I use two `$` inside the password. The password is written in a separate file that is passed with `env_file`

transmission.env:
```
USER=admin
PASS=test12$$
```

Using this as password will change the username to `root`. If you prefer I can contact you on discord.

**Comment by adripo** [comment] 2022-11-02 00:01
I found out that the problem explained in my [hidden message above](https://github.com/linuxserver/docker-transmission/issues/212#issuecomment-1299356086) persists even without using `$$` inside the password
