### ISSUE TITLE
[BUG] Regression with `PUID` support in v4.0.6

### ISSUE THREAD

**Issue by rpatterson** [linuxserver/docker-transmission#284] opened 2024-08-06 17:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `# transmission-daemon` process is running as UID `911`, not the UID specified in the `PUID` environment variable.

### Expected Behavior

The `# transmission-daemon` process should run as the UID specified in the `PUID` environment variable.

### Steps To Reproduce

1. Take a working compose project that specifies the `PUID` environment variable
2. Run it under v4.0.5, note that Transmission can write to files owned by the `PUID`
3. Run it under v4.0.6, note that Transmission can no longer write to files owned by the `PUID`

### Environment

- OS:

```console
# cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

- How docker service was installed:

```console
# dpkg -S $(which dockerd)
docker-ce: /usr/bin/dockerd
# apt policy docker-ce
docker-ce:
  Installed: 5:27.1.1-1~ubuntu.22.04~jammy
  Candidate: 5:27.1.1-1~ubuntu.22.04~jammy
  Version table:
 *** 5:27.1.1-1~ubuntu.22.04~jammy 500
        500 https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
        100 /var/lib/dpkg/status
...
```

### CPU architecture

x86-64

### Docker creation

https://gitlab.com/rpatterson/prunerr/-/blob/develop/docker-compose.yml?ref_type=heads#L8

### Container logs

I no longer have the logs, but it printed something like `/config/settings.json: permission denied`

**Comment by j0nnymoe** [comment] 2024-08-06 18:25
We need to have the container start up logs, it'll show the set PUID/PGID.

**Comment by Roxedus** [comment] 2024-08-06 18:28
Cannot reproduce, need logs.
```sh
root@dfe0f4840ba9:/# ls -la /downloads/complete/
total 1155136
drwxr-xr-x 2 abc users       4096 Aug  6 18:25 .
drwxr-xr-x 4 abc users       4096 Aug  6 18:22 ..
-rw-rw-r-- 1 abc users 1182826496 Aug  6 18:25 archlinux-2024.08.01-x86_64.iso
root@dfe0f4840ba9:/# echo "$PUID $PGID"
1000 1000
root@dfe0f4840ba9:/# cat /build_version
Linuxserver.io version: 4.0.6-r0-ls249
```

**Comment by rpatterson** [comment] 2024-08-06 19:10
> Cannot reproduce, need logs.

Your output doesn't demonstrate what UID the `abc` user has. When I had the issue, it was `911`, not the `PUID` I set.

Apologies, I don't have time at the moment for followup, especially since I can use `image: "linuxserver/transmission:4.0.5"` as a workaround. I think as a maintainer, however, you might want to be concerned about this and not close this out of hand. Because of how poorly behaved Transmissions is, this `PUID` regression meant *all* my `/config/resume/*.resume` files were rewritten with defaults which means I lost all my per-torrent `downloadDir` settings, added and done dates, etc.. This is a serious PITA to restore for my 3k torrents!

**Comment by Roxedus** [comment] 2024-08-06 19:24
Without logs we cannot be sure the envs were set correctly, thus we do not have any workable info to confirm this is a bug. There was no change in how dropping permissions were handled in this image between .5 and .6. 
```sh
abc@dfe0f4840ba9:/$ id
uid=1000(abc) gid=1000(users) groups=1000(users)
abc@dfe0f4840ba9:/$ echo "$PUID $PGID"
1000 1000
abc@dfe0f4840ba9:/$ ls -la /downloads/complete/
total 1155136
drwxr-xr-x 2 abc users       4096 Aug  6 18:25 .
drwxr-xr-x 4 abc users       4096 Aug  6 18:22 ..
-rw-rw-r-- 1 abc users 1182826496 Aug  6 18:25 archlinux-2024.08.01-x86_64.iso
```
Im fine with letting this wither away into the abyss, in the hopes that there's logs the next time someone potentially reports  the same happening.

**Comment by positiveque** [comment] 2024-08-06 21:10
Hello! I tried docker compose with PUID & PGID=0 and without this env. The error persists regardless. It appeared today after the last image update transmission:latest.

Container:

`root@bf86e3806aa8:/# id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)

root@bf86e3806aa8:/# ls -la downloads

total 4315960
drwxr-xr-x 12 abc  abc       24576 Aug  6 11:03  .
drwxr-xr-x  1 root root       4096 Aug  6 22:50  ..
drwxrwxr-x  5 root root       4096 Jul 14 13:55 'FileName (2022)'
drwxrwxr-x  5 root root       4096 Jul 14 13:55 'FileName (2023)'
`

Logs:

`Container started
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
all values are hidden
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
all values are hidden
   Brought to you by linuxserver.io
───────────────────────────────────────
all values are hidden
To support LSIO projects visit:
https://www.linuxserver.io/donate/
all values are hidden
───────────────────────────────────────
GID/UID
───────────────────────────────────────
all values are hidden
**User UID:    911
User GID:    911**
───────────────────────────────────────
Linuxserver.io version: 4.0.6-r0-ls249
Build-date: 2024-08-06T10:36:53+00:00
───────────────────────────────────────
    
ln: failed to create symbolic link '/transmissionic/index.html': File exists
ln: failed to create symbolic link '/combustion-release/index.html': File exists
ln: failed to create symbolic link '/flood-for-transmission/index.html': File exists
ln: failed to create symbolic link '/kettu/index.html': File exists
ln: failed to create symbolic link '/transmission-web-control/index.html': File exists
[custom-init] No custom files found, skipping...
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
[ls.io-init] done.
**tail: invalid PID: ‘’**
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
**tail: invalid PID: ‘’**
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
**tail: invalid PID: ‘’`**

**Comment by Roxedus** [comment] 2024-08-06 21:21
Your id command is run as root, it will always say 0:0. Docker exec as the abc user

**Comment by Roxedus** [comment] 2024-08-06 22:01
I don't get these with 4.0.6-r0-ls249.  As logs are missing from OP, I assume this issue is unrelated, open a new issue following the template.

**Comment by zwimer** [comment] 2024-08-07 01:06
This happens for me as well with the new update, it also triggers transmission to restart. Not the container, the container never dies, the transmission process seems to restart; the linuxserver logo does not reappear in the logs either.

**Comment by MorganMLGman** [comment] 2024-08-07 06:27
I have the same issue. No changes in compose file. Watchtower pulled new image at 2AM and transmission died.
![image](https://github.com/user-attachments/assets/eda265ab-2ddd-4132-867e-f77681ebc159)

**Comment by MorganMLGman** [comment] 2024-08-07 06:30
`4.0.6-r0-ls248` and no `tail: invalid PID ''` with the same compose file.
![image](https://github.com/user-attachments/assets/13730017-d9e5-4776-be87-946bf5862cd3)

**Comment by sstrang** [comment] 2024-08-07 07:37
I pulled the latest image earlier today, and can confirm the same issue in my logs as [MorganMLGman](https://github.com/MorganMLGman). Reverting to an earlier version has stopped the repeated crashing of the Transmission process within the container.

**Comment by Roxedus** [comment] 2024-08-07 07:50
There is a issue in transmission, but not at all related to PUID support, none of the comments has proven that.
The PID errors are due to transmission dying, https://github.com/transmission/transmission/issues/7035.

This issue has become a mess, as no one has opened a separate issue regarding the actual bug in transmission, when prompted to do so. I am therefore closing this issue, and hope someone can open a proper issue(logs and all) here regarding the PID, so it can be pinned.



__Please do not comment on the most recent issue with logs and behavior that DO NOT mimic the issue in the slightest.__

**Closed by Roxedus** 2024-08-07 07:50 UTC

**Comment by MorganMLGman** [comment] 2024-08-07 08:15
New issue [](https://github.com/linuxserver/docker-transmission/issues/285)

**Comment by j0nnymoe** [comment] 2024-08-07 08:40
@MorganMLGman Rox has already posted that this is an upstream issue and not a problem with the container.
