### ISSUE TITLE
Transmission 3.00 released

### ISSUE THREAD

**Issue by bagobones** [linuxserver/docker-transmission#111] opened 2020-05-22 21:12 UTC
Probably only safe for testing at this point but wanted to point out it was available and the first major release in a VERY long time. I believe this is also the first public release since they moved development to github.

https://github.com/transmission/transmission/releases

**Comment by aptalca** [comment] 2020-05-22 21:13
duplicate of #109

**Closed** 2020-05-23 03:23 UTC
