### ISSUE TITLE
HTTPS issues connecting to tracker 

### ISSUE THREAD

**Issue by AvadaKedavra404** [linuxserver/docker-transmission#94] opened 2020-02-07 01:26 UTC
In trying to connect to a private tracker to download a .torrent file, Transmission returns:
```
Error adding "https://______"
gotMetadataFromURL: http error 0: No Response
```
Likewise if I download the .torrent file through my browser and then upload it to Transmission, the torrent adds itself but then errors out:
```
Tracker returned an error: Tracker gave HTTP response code 0 (No Response)'. 
```
I tested whether I can `wget` the file through ssh directly on my Synology and that works fine.
If I `wget` inside the docker-transmission container, it errors out:
```
Connecting to ____                                                                                                                       
wget: error getting response: Connection reset by peer 
```

The issue seems to be related to HTTPS connections through this Transmission docker only. Any help here would be hot.

## Environment
**OS:** DSM 6.2.2 Update 4     
**CPU architecture:** x64   
**How docker service was installed:** Docker GUI on DSM     

## Command used to create docker container (run/create/compose/screenshot)

The equivalent of this in GUI form:
```
docker create \
  --name=transmission \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -v <path to data>:/config \
  -v <path to downloads>:/downloads \
  -v <path to watch folder>:/watch \
  --restart unless-stopped \
  linuxserver/transmission
```
With the `Bridge Network` checkbox enabled.

You're my only hope.

**Comment by drizuid** [comment] 2020-04-04 19:16
I am unable to reproduce this on a debian or ubuntu host. This issue could be specific to synology

**Comment by x-Felix** [comment] 2020-08-06 05:58
I have the same issue with latest 3.0.0 build. 
I believe this is due to alpine image and libcurl not able to verify SSL certificates. ca-certificates is not included in this transmission image. Or need to add env to not verify SSL cert.

**Comment by drizuid** [comment] 2020-08-06 12:56
> I have the same issue with latest 3.0.0 build.
> I believe this is due to alpine image and libcurl not able to verify SSL certificates. ca-certificates is not included in this transmission image. Or need to add env to not verify SSL cert.

I use the latest build with ssl trackers fine. (as do MANY of our users) I'm going to close this and if you have an issue, you can open a new issue and provide logs/compose etc, but i can definitively tell you, "https" works fine

**Closed by drizuid** 2020-08-06 12:56 UTC
Labels: no-issue-activity

**Comment by pandvan** [comment] 2020-08-09 17:28
> Or need to add env to not verify SSL cert.
Sorry to reply on this already closed ticket. I've encountered the same issue because the tracker I'm trying to download to uses a self-signed certificate. As of Transmission 3.00 SSL verification is enabled by default.
A workaround that I tried and worked consists on set the `TR_CURL_SSL_NO_VERIFY` env variable to `1`
