### ISSUE TITLE
[BUG] s6-notifyoncheck SIGKILL

### ISSUE THREAD

**Issue by bacontrees** [linuxserver/docker-transmission#279] opened 2024-05-28 21:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every few minutes, Transmission reloads with the following logged:

```
./run: line 8:  8259 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
s6-supervise svc-transmission: warning: finish script lifetime reached maximum value - sending it a SIGKILL
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
```

When this happens, download data is frequently corrupted (needs local verify or even says no data found).  This system has been running its current configuration for approximately a month without issue and only became problematic recently.

### Expected Behavior

Transmission stays alive, does not SIGKILL.

### Steps To Reproduce

In Mint 21.3 environment with Docker's official apt repository installed, run Transmission connected to in-service VPN.  After a few minutes, s6 kills/restarts Transmission, causing download data corruption (needs local verify or even says no data found).

### Environment

```markdown
- OS: Mint 21.3 (Ubuntu 22.04 jammy)
- How docker service was installed: Docker's apt repository
- How Transmission reaches internet: In-service VPN container to prevent IP leakage
```

### CPU architecture

x86-64

### Docker creation

```bash
services:

  vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            - /mnt/SATA_SSD/docker-appdata/transmission/pia-dat:/pia
            - /mnt/SATA_SSD/docker-appdata/transmission/pia-port:/pia-shared
        ports:
            - "9091:9091/tcp"
        cap_add:
            - NET_ADMIN
        environment:
            - LOCAL_NETWORK=LOCAL_SUBNET/24
            - LOC=REDACTED
            - USER=REDACTED
            - PASS=REDACTED
            - PORT_FORWARDING=1
            - PORT_PERSIST=1
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=REDACTED
    env_file:
      - /mnt/SATA_SSD/docker-appdata/transmission/transmission.env
    volumes:
      - /mnt/SATA_SSD/docker-appdata/transmission/transmission-config:/config
      - /mnt/SATA_SSD/docker-appdata/transmission/downloads:/downloads
      - /mnt/SATA_SSD/docker-appdata/transmission/watch:/watch
      - /mnt/SMB_Synology:/mnt/SMB_Synology
      - /mnt/SMB_Synology:/data
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
[ls.io-init] done.
./run: line 8:   173 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
s6-supervise svc-transmission: warning: finish script lifetime reached maximum value - sending it a SIGKILL
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
```

**Comment by bacontrees** [comment] 2024-06-10 13:28
Issue persists on fresh Debian 12 installation as well.

**Comment by 6cUbi57z** [comment] 2024-07-03 09:58
I'm experiencing this without the VPN. It seems that transmission is becoming a zombie process.

In my k8s cluster, this is preventing the pod from closing. The only way I've found to resolve the issue is to restart the host.

**Comment by 6cUbi57z** [comment] 2024-07-03 10:54
I noticed some log messages in the terminal of the host possibly indicating this: https://github.com/transmission/transmission/issues/1007

I've changed the `preallocation` to 0 and have restarted.

**Comment by 6cUbi57z** [comment] 2024-08-03 19:28
Still an issue although preallocation 0 may help improve stability.

**Comment by PHLAK** [comment] 2024-08-08 05:18
I just noticed this issue in the last day or two. Rolling back to the `4.0.5` tag seems to be working without issue for me for now.

**Closed** 2024-11-06 19:16 UTC
Labels: no-issue-activity, closed-issue-activity

**Comment by PHLAK** [comment] 2024-11-14 22:42
This is still an issue it seems.

**Comment by bacontrees** [comment] 2024-11-14 23:19
FWIW, my particular issue was resolved ultimately by creating a new, empty Torrents directory and setting that as the default ¯\_(ツ)_/¯
