### ISSUE TITLE
where is transmission.log file ??

### ISSUE THREAD

**Issue by iruahn** [linuxserver/docker-transmission#166] opened 2021-07-07 14:08 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

/config dir has transmission.log file.

## Current Behavior

Any folder doesn't have transmission.log file.

## Steps to Reproduce

1. execute docker transmission
2. check transmission.log in /config dir
3.
4.

## Environment
**OS:** Synology DSM 7.0
**CPU architecture:** x86_64. (Geminilake)
**How docker service was installed:** Synology Docker Package

## Command used to create docker container (run/create/compose/screenshot)

sudo docker run -d --name=transmission -e PUID=1000 -e PGID=1000 -e TZ=Asia/Seoul -e TRANSMISSION_WEB_HOME=/combustion-release/ -e USER=iruahn -e PASS=1399 -p 9092:9091 -p 51413:51413 -p 51413:51413/udp -v homes/iruahn/Drive/TransmissionConfig:/config -v homes/iruahn/Drive/Downloads:/downloads -v homes/iruahn/Drive/WatchTorrentFile:/watch --restart unless-stopped ghcr.io/linuxserver/transmission

## Docker logs

![스크린샷 2021-07-07 오후 11 07 12](https://user-images.githubusercontent.com/53987596/124773700-241ecd00-df78-11eb-9d86-b9a675985c54.png)

**Comment by 0b100100** [comment] 2021-07-09 16:09
duplicate of https://github.com/linuxserver/docker-transmission/issues/155

**Comment by thelamer** [comment] 2022-02-21 20:07
User docker logs, we run the PID in the foreground.

**Closed by thelamer** 2022-02-21 20:07 UTC
Labels: no-issue-activity
